language: php

php:
  - 7.0 # EOL
  - 7.1 # EOL
  - 7.2 # Until 30 Nov 2020
  - 7.3 # Until 6 Dec 2021
  - 7.4 # Until 28 Nov 2022

addons:
  apt:
    packages:
      - parallel

env:
  global:
    - PHPUNIT_VERSION="~7|~8"
    - COMPOSER_CACHE_DIR=/home/travis/.composer
    - WP_VERSION=5.3

matrix:
  include:
    # see https://codex.wordpress.org/WordPress_Versions
    # see https://phpunit.de/upported-versions.html
    - php: 7.0
      env: WP_VERSION=4.5
    - php: 7.0
      env: WP_VERSION=4.7
    - php: 7.1
      env: WP_VERSION=4.8
    - php: 7.2
      env: WP_VERSION=4.9
    - php: 7.3
      env: WP_VERSION=5.1
  # Do not wait for allowed failures
  fast_finish: true

services:
  - mysql

cache:
  directories:
    - /home/travis/.composer

before_install:
  - mysql -e 'CREATE DATABASE dev;'

install:
  - composer install
  # Using WP-CLI instead of Composer because this way we can use the env matrix (above).
  - vendor/bin/wp --allow-root core download --version=$WP_VERSION
  - vendor/bin/wp --allow-root config create --force --dbuser=travis --dbpass="" --dbhost="127.0.0.1" --skip-check
  - vendor/bin/wp --allow-root core install --skip-email

script:
  - composer validate --strict --no-check-lock
  - vendor/bin/phpunit --coverage-clover coverage.xml
  # Old phpstan is givin so much trouble so we cut out PHP <= 7.1
  - php -r 'exit(intval(PHP_VERSION_ID >= 70100));' || vendor/bin/phpstan analyse lib/

after_script:
  # upload coverage.xml file to Coveralls to analyze it
  - vendor/bin/coveralls --verbose

after_failure:
  - cat srv/wp-content/debug.log || true
